Gopkg.lock, storage/interfaces.go, storage/mocks/segment.go, storage/mutexmap/segments.go, storage/mutexmap/segments_test.go, storage/mutexmap/splits.go, storage/redis/segments.go, storage/redis/segments_test.go
=> added ismember logic

CHANGES, provisional/impcounter.go, provisional/impcounter_test.go, util/time.go, util/time_test.go
=> added impressionsCounter

provisional/impmanager.go, provisional/impmanager_test.go, service/api/http_recorders.go, service/api/http_recorders_test.go, service/interfaces.go, service/mocks/impression.go, synchronizer/manager_test.go, synchronizer/synchronizer_test.go, synchronizer/worker/impression/single.go, synchronizer/worker/impression/single_test.go, tasks/impressionsync_test.go, util/mode.go
=> added header for testImpressions/bulk

conf/conf.go, conf/defaults.go, provisional/impmanager.go, provisional/impmanager_test.go, util/mode.go
=> added support for splitSync and added flag for listenerEnabled

conf/conf.go, service/api/http_recorders.go, service/interfaces.go, service/mocks/telemetry.go, telemetry/constants.go, telemetry/init.go, telemetry/init_test.go, telemetry/interfaces.go
=> added init

go.mod, go.sum, push/manager.go, push/manager_test.go, push/statustracker.go, push/statustracker_test.go, storage/inmemory/telemetry.go, storage/inmemory/telemetry_test.go, storage/interfaces.go, storage/mocks/telemetry.go, synchronizer/manager.go, synchronizer/manager_test.go
=> added tracking for streaming_events

CHANGES
=> updated changelog

.github/workflows/ci-cd.yml, .travis.yml
Adding new ci-cd workflow for GHA in order to migrate out of TravisCI
How do we test the changes introduced in this PR?
Verifying that the build pass ok in the GHA actions tab and checking SonarQube
=> GHA Migration - Ci-Cd workflow added

healthcheck/application/monitor.go, healthcheck/mocks/applicationmonitor.go, healthcheck/mocks/servicesmonitor.go, healthcheck/services/monitor.go, synchronizer/local.go, synchronizer/synchronizer_test.go, synchronizer/worker/segment/segment.go, synchronizer/worker/segment/segment_test.go, synchronizer/worker/split/split.go, synchronizer/worker/split/split_test.go, tasks/segmentsync_test.go, tasks/splitsync_test.go
- [ x] New feature
- Added Healthcheck monitor interfaces
- Updated Fetchers to notify event
=> [HM] Added interfaces

.github/workflows/ci.yml
Some fixes for the previous PR
=> workflow renamed and coverage before

CHANGES, service/api/http_fetchers.go, service/api/http_fetchers_test.go, service/commons.go, service/interfaces.go, service/local/splitFetcher.go, service/local/splitFetcher_test.go, service/mocks/segment.go, service/mocks/split.go, synchronizer/synchronizer_test.go, synchronizer/worker/segment/segment.go, synchronizer/worker/segment/segment_test.go, synchronizer/worker/split/split.go, synchronizer/worker/split/split_test.go, tasks/segmentsync_test.go, tasks/splitsync_test.go
=> added FetchOptions in prep for CDN Bypass

dtos/telemetry.go, service/api/http_recorders.go, service/api/http_recorders_test.go, service/interfaces.go, service/mocks/telemetry.go
=> Add method to post the unique keys in HttpRecord component

CHANGES, push/borrowed.go, push/mocks/sync.go, synchronizer/local.go, synchronizer/manager.go, synchronizer/manager_test.go, synchronizer/mocks/mocks.go, synchronizer/synchronizer.go, synchronizer/synchronizer_test.go, synchronizer/worker/segment/segment.go, synchronizer/worker/segment/segment_test.go
=> Cdn bypass

telemetry/localhost.go
=> added no op for localhost mode

conf/conf.go, synchronizer/synchronizer_test.go, synchronizer/worker/impression/single.go, synchronizer/worker/impression/single_test.go, tasks/impressionsync_test.go, telemetry/constants.go, telemetry/helpers.go, telemetry/memory.go, telemetry/memory_test.go, util/mode.go
=> Add new impression mode: none and config cleanup

provisional/strategy/optimized.go, provisional/strategy/uniquekeystracker.go, storage/interfaces.go, storage/mocks/filter.go, storage/mocks/telemetry.go, storage/redis/constants.go, storage/redis/telemetry.go, storage/redis/telemetry_test.go, tasks/uniquekeyssync.go, tasks/uniquekeyssync_test.go, telemetry/helpers.go, telemetry/interface.go, telemetry/memory.go, telemetry/redis.go
=> [redis] Add component to write the bulks of unique keys

go.mod, go.sum, provisional/strategy/none.go, storage/inmemory/telemetry.go, storage/interfaces.go, storage/redis/constants.go, storage/redis/impressionscount.go, storage/redis/impressionscount_test.go, storage/redis/telemetry.go, synchronizer/redis.go, synchronizer/redis_test.go, synchronizer/synchronizer.go, synchronizer/worker/impressionscount/redis.go, tasks/cleanfiltersync.go, tasks/cleanfiltersync_test.go, tasks/impressionscountsync.go, tasks/impressionscountsync_test.go, tasks/uniquekeyssync_test.go, telemetry/localhost.go
=> [Client][redis] implement deduping logic in redis mode

.github/workflows/ci.yml, CHANGES, conf/defaults.go, service/api/auth.go, service/api/auth_test.go
=> removed v2 from path

storage/interfaces.go, storage/mocks/impressionscount.go, storage/redis/impressionscount.go, storage/redis/impressionscount_test.go, synchronizer/worker/impressionscount/redis.go, synchronizer/worker/impressionscount/redis_test.go, synchronizer/worker/impressionscount/single.go
=> Add impcount consumer storage

push/parser.go, push/parser_test.go
=> adding New method

CHANGES
=> Added Changes.

CHANGES, go.mod, go.sum
=> replaced murmur332 library

service/local/splitFetcher.go, service/local/splitFetcher_test.go, testdata/splitChange_mock.json
- New feature: Add a new split fetcher for JSON localhost
Add test case in splitFetcher_test
=> [SDKS-6442] Add split fetcher for json localhost

service/local/mocks/mocks.go, service/local/reader.go, service/local/segmentFetcher.go, service/local/segmentFetcher_test.go, testdata/segmentTillInvalid.json
- New feature: Add localhost json segment parser and fetcher 
Add test case in segementFetcher_test.
=> [SDKA-6448] Add segment parser and fetcher

service/local/splitFetcher.go, service/local/splitFetcher_test.go, service/local/util.go, service/local/util_test.go, synchronizer/local.go
- New feature: Updated Local to fetch segments. Also, created an until to have the DefineFormat.
Added util_test to check the DefineFormat method
=> [SDKS-6546] Update local file for segments

synchronizer/local.go
- New feature: Add new logic for new localhostRefreshEnabled in local.go.
=> [SDKS-6544] Add new config localhostRefreshEnabled

service/local/sanitizer.go, service/local/segmentFetcher.go, service/local/segmentFetcher_test.go, service/local/splitFetcher.go, service/local/splitFetcher_test.go, testdata/segmentSanitization.json, testdata/segmentWithoutName.json
- New feature: Split and Segment Sanitization
Added test cases in splitFetcher_test and segmentFetcher_test.
=> [SDKS-6472] Add split and segment sanitization

service/local/segmentFetcher.go, synchronizer/manager.go
- New feature: Localhost, update manager to handler errors
=> [SDKS-6573] Update manager to handler error

service/local/segmentFetcher.go, service/local/splitFetcher.go, synchronizer/worker/segment/errorUtil.go
Added mutex to hash map in segment and split fetchers
=> Add mutex to hash map in segment and split fetchers

storage/redis/telemetry.go, storage/redis/telemetry_test.go
=> Updated mtk dto in redis

push/parser.go
- New feature: Instant feature flags
=> [SDKS-7067] Add new properties to BaseUpdate and genericMessageData

storage/redis/redis.go
=> [SDKS-7099] Update Redis connection error message

CHANGES, telemetry/redis.go, telemetry/redis_test.go
Add this case in redis_test.go.
=> Fix save impression mode in Redis

push/manager.go, push/manager_test.go, push/processor.go, push/processor_test.go, push/split.go, push/split_test.go, synchronizer/local.go, synchronizer/manager.go, synchronizer/synchronizer_test.go
=> removed unused splitStorage and monitor from manager and processor

synchronizer/synchronizer_test.go
Add test case for iff when fetching segments
=> [SDKS-7069]Add test case TestSplitUpdateWithReferencedSegments

dtos/split.go, go.mod, go.sum, storage/redis/constants.go, storage/redis/splits.go, storage/redis/splits_test.go
=> [WIP] Support for Redis FlagSet on Update

conf/conf.go, service/api/http_fetchers.go, service/api/http_fetchers_test.go, service/commons.go
=> [WIP] Added FlagSetsFilter

dtos/telemetry.go, storage/inmemory/telemetry.go, storage/inmemory/telemetry_test.go, telemetry/constants.go, telemetry/constants_test.go
=> flagsets telemetry

engine/evaluator/evaluator_test.go, go.mod, go.sum, storage/inmemory/mutexmap/splits.go, storage/inmemory/mutexmap/splits_test.go, storage/interfaces.go, storage/mocks/split.go, storage/redis/splits.go, storage/redis/splits_test.go
- New feature: getNamesByFlagSets in storage
Add tests in splits_test
=> [SDKS-7681] Add getNameByFlagSets in storages

storage/redis/splits_test.go
Integration tests with Redis Added
=> Integration Tests with redis added

engine/evaluator/evaluator.go, engine/evaluator/evaluator_test.go, flagsets/flag_set_validator.go
- New feature: Add EvaluateFeatureByFlagSets and GetFeatureFlagNamesByFlagSets in evaluator.go
Add test cases in evaluator_test.
=> [SDKS-7679] Add EvaluateFeatureByFlagSets in the Evaluator

dtos/flag_set_validator.go, flagsets/flag_set_validator.go
=> Add FlagSetValidationError

dtos/telemetry.go, telemetry/constants.go, telemetry/memory.go, telemetry/redis.go
-  New feature: Add FlagSetsTotal  and FlagSetsInvalid in config  init.
=> [SDKS-7683] Add FlagSetsTotal and FlagSetsInvalid in init config for telemetry

engine/evaluator/evaluator.go
=> [SDKS-7688] Fix getFeatureFlagsNamesByFlagSets

telemetry/constants.go, telemetry/constants_test.go
=> fixing redis sync

conf/conf.go, storage/redis/splits.go, storage/redis/splits_test.go
=> Using scan instead of keys

CHANGES, conf/conf.go, go.mod, storage/redis/splits.go, storage/redis/splits_test.go
=> Fixing synchronizer dashboard

engine/evaluator/impressionlabels/impression_labels.go
Add label for Unsupported Matchers.
=> Add label UnsupportedMatcherType

engine/grammar/matchers/matchers.go, engine/grammar/matchers/semver.go, engine/grammar/matchers/semver_test.go
Added in list semver in semver.go
Added test cases in semver_test.go
=> [SDKS-8368] Add in list semver

engine/validator/matchers.go, engine/validator/matchers_test.go
=> added unsupported improvements

engine/grammar/condition.go, engine/grammar/condition_test.go, engine/grammar/matchers/datatypes/unsupportedmatchererror.go, engine/grammar/matchers/matchers.go, engine/grammar/split.go, engine/grammar/split_test.go, engine/validator/matchers.go
=> [SDKS-8369] Update NewSplit to check unsupported matcher

synchronizer/local.go, synchronizer/local_test.go, synchronizer/synchronizer_test.go, synchronizer/worker/segment/segment.go, synchronizer/worker/segment/segment_test.go, tasks/segmentsync.go, tasks/segmentsync_test.go
=> [Bugfix] SDKS-8851- Health monitor don't account for cases with no segments

storage/inmemory/mutexmap/large_segments.go, storage/inmemory/mutexmap/large_segments_test.go, storage/interfaces.go
=> [SDKS-8965] Large segments in memory storage implementation

engine/grammar/matchers/inlargesegment.go, engine/grammar/matchers/inlargesegment_test.go, engine/grammar/matchers/matchers.go, service/api/client.go, service/api/specs/splitversionfilter.go, service/api/specs/splitversionfilter_test.go, storage/inmemory/mutexmap/largesegments.go, storage/inmemory/mutexmap/largesegments_test.go, storage/interfaces.go, synchronizer/worker/largesegment/largesegment.go, synchronizer/worker/largesegment/largesegment_test.go
=> Large segmet matcher implementation

conf/conf.go, conf/defaults.go, dtos/largesegment.go, dtos/notification.go, dtos/notification_test.go, push/borrowed.go, push/largesegment.go, push/largesegment_test.go, push/manager.go, push/manager_test.go, push/mocks/sync.go, push/parser.go, push/parser_test.go, push/processor.go, push/processor_test.go, synchronizer/manager_test.go
=> [SDKS-8929] Streaming support for Large Segments

conf/conf.go, conf/defaults.go, push/processor.go, push/processor_test.go, service/api/http_fetchers.go, service/api/http_fetchers_test.go, synchronizer/local.go, synchronizer/manager.go, synchronizer/manager_test.go, synchronizer/mocks/mocks.go, synchronizer/synchronizer.go, synchronizer/synchronizer_test.go
=> pr feedback

dtos/impression.go, dtos/split.go, engine/evaluator/evaluator.go, engine/grammar/split.go, provisional/impmanager.go, provisional/impmanager_test.go, provisional/strategy/none.go, provisional/strategy/optimized.go
=> [SDKS-9120] Impression per toggle implementation

.github/workflows/ci.yml, dtos/rulebasedsegment.go
=> Add rule based segment dtos

.github/workflows/ci.yml, service/api/specs/specversion.go, service/api/specs/specversion_test.go
- Added 1.3 spec version for rule-based
- Updated test cases.
=> [FME-4342] Add spec version

storage/interfaces.go, storage/redis/constants.go, storage/redis/rulebasedsegment_test.go, storage/redis/rulebasedsegments.go
- Added rule-baed segment for Redis.
- Added test cases in rulebasedsegment_test.go
=> [FME-9624] Add rule-based segment for redis

engine/grammar/inrulebasedsegment.go, service/api/specs/specversion.go
=> Update import slice

engine/evaluator/evaluator.go, engine/evaluator/evaluator_test.go, engine/evaluator/impressionlabels/impression_labels.go, engine/grammar/rulebuilder.go, engine/grammar/split.go
- Added logic in evaluator
- Added test cases in evaluator_test.go
=> [FME-10090] Added prerequisites logic in the evaluator
